### ISSUE TITLE
115浏览器登录后把document.cookie 提取到 ./~115.cookies.json 也无法登录

### ISSUE THREAD

**Issue by waltcow** [coolzilj/lixian-115#2]

**Comment by coolzilj** [comment]
确实通过 document.cookie 取到的值貌似缺了几个关键的 key, 所以不视为正常登录，这个问题有待调查。
你可以通过 http://www.editthiscookie.com/ 插件去导出 cookie，个人亲测有效

**Comment by coolzilj** [comment]
@waltcow 刚刚已经更新了一下代码，你可以按照我上面说的再试一下。
提醒一下，`.115.cookies` 文件应该放在你的 home 目录下，详看 README
