### ISSUE TITLE
有bug 求解决

### ISSUE THREAD

**Issue by code-geeker** [coolzilj/lixian-115#3]
![Alt text](http://puu.sh/onSTd/ea3b46149e.png)

![Alt text](http://puu.sh/onSTJ/d7da779390.png)

**Comment by coolzilj** [comment]
应该是登录验证失败。
登录的方法是，直接把 cookie，放到 ~/.115.cookies 里

**Comment by code-geeker** [comment]
已经放进去了的  
![](http://puu.sh/onUod/6c376ea780.png)

`[
{
    "domain": ".115.com",
    "hostOnly": false,
    "httpOnly": true,
    "name": "CID",
    "path": "/",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "1c82caf930baaacd2a40dec330760c47",
    "id": 1
},
{
    "domain": ".115.com",
    "expirationDate": 1461488820,
    "hostOnly": false,
    "httpOnly": false,
    "name": "OOFL",
    "path": "/",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "591196820",
    "id": 2
},
{
    "domain": ".115.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "PHPSESSID",
    "path": "/",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "idv1ha1bbapcag4lso1p5pfad7",
    "id": 3
},
{
    "domain": ".115.com",
    "hostOnly": false,
    "httpOnly": true,
    "name": "SEID",
    "path": "/",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "f690fc8b509bc1313c7804dae3aed122a07fb5b9b189a16ff1de2d0eea46fccc79815d9b65abfd6fe1bf2fa1714d56666a4f88b9d3556a1c2fdfa2",
    "id": 4
},
{
    "domain": ".115.com",
    "expirationDate": 1462352880,
    "hostOnly": false,
    "httpOnly": false,
    "name": "ssov_591196820",
    "path": "/",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "0_591196820_49b655cf6c6beb621e66fa9990d352",
    "id": 5
},
{
    "domain": ".115.com",
    "hostOnly": false,
    "httpOnly": true,
    "name": "UID",
    "path": "/",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "591196820_A1_146156312",
    "id": 6
},
{
    "domain": "115.com",
    "expirationDate": 1461057460.652634,
    "hostOnly": true,
    "httpOnly": false,
    "name": "591196820_settings",
    "path": "/",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "b6589fc6ab0dc82cf12099d1c2d40994e8410c",
    "id": 7
}
]`

**Comment by coolzilj** [comment]
目前只处理分号分割的格式，

```
a=1;b=2;c=3;
```

如果你用 EditThisCookie 导出的话可以选择导出格式
![image](https://cloud.githubusercontent.com/assets/1059327/14635611/bf67d2d2-0659-11e6-8967-d02c039a4adc.png)

**Comment by code-geeker** [comment]
可以了 thx
